# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd dist
    - run: ls - la
    - run: npm i
    - run: pwd
    - run: which ls
    - run: npm run build --if-present
    - run: cp ./dist/angular-deploy-github-self-host /usr/share/nginx/html 
   # - run: sudo cp ./_work/angular-deploy-github-self-host/dist/angular-deploy-github-self-host ~/usr/share/nginx/html
    - run: sudo systemctl stop nginx && sudo systemctl start nginx
