# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: use node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls -la
    - run: npm i
    - run: pwd
    - run: which ls
    - run: npm run build
    - run: ls -la
    - run: cp -r ./dist/angular-deploy-github-self-host/ /usr/share/nginx/html 
    - run: systemctl restart nginx
